# Generated by Django 5.0.1 on 2024-01-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificados',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
