# Generated by Django 5.0.1 on 2024-01-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibv2', '0002_classificados_titulo_eventos_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destaque',
            old_name='tituto',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='publicacoes',
            old_name='tituto',
            new_name='titulo',
        ),
    ]
