# Generated by Django 5.0.1 on 2024-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibv2', '0003_rename_tituto_destaque_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificados',
            name='contato',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
